### ISSUE TITLE
dictionaryapi response changed + consider mocking out requests response

### ISSUE THREAD

**Issue by bbelderbos** [PyBites-Open-Source/pybites-tools#28]
@rhyspowell regarding the meaning tool, this test / API request now returns a 404 (instead of a 200):

```
        (
            argparse.Namespace(lang="de", origin=False, word="danke"),
            "zur Unterstreichung einer höflichen Ablehnung oder Annahme eines Angebots o. Ä.",
        ),
```

Also the API response seems to have changed since you wrote this tool causing [the tests to fail](https://github.com/PyBites-Open-Source/pybites-tools/runs/5821640098?check_suite_focus=true):

```
> /Users/bbelderbos/code/pybites-tools/pybites_tools/meaning.py(28)get_meaning()
-> origin = "No origin information available"
(Pdb) "origin" in data[0]
False
(Pdb) type(data[0])
<class 'dict'>
(Pdb) data[0].keys()
dict_keys(['word', 'phonetic', 'phonetics', 'meanings', 'license', 'sourceUrls'])
```

Could you check please?

Thanks!
Bob

**Comment by rhyspowell** [comment]
@bbelderbos Looks like they have scaled things back to just en. I will remove the german test but it might be a nice little project to recreate the tool but in python!

**Comment by bbelderbos** [comment]
Ah you mean to figure out what they are using and build our own API?

**Comment by rhyspowell** [comment]
https://github.com/PyBites-Open-Source/pybites-tools/pull/29

For fix

As for how they do it, they scrape google, I just looked at their code. We can't reuse it as its JS, well we could but thats not really python tools 😂

**Comment by bbelderbos** [comment]
OK thanks for fixing (approved) and checking, so we keep using them, or could we use a library like BeautifulSoup ourselves here?

**Comment by bbelderbos** [comment]
@rhyspowell do we want to make more changes for this issue?

**Comment by rhyspowell** [comment]
@bbelderbos will refresh where we were and see what I can do

**Comment by bbelderbos** [comment]
Cool, no rush on this of course

**Comment by rhyspowell** [comment]
@bbelderbos #37 for your approval. If it looks good there are more options that we can add
