### ISSUE TITLE
Get tox + GitHub Actions working for this project

### ISSUE THREAD

**Issue by bbelderbos** [PyBites-Open-Source/pybites-tools#6]
Just added it as part of this PR:
https://github.com/PyBites-Open-Source/pybites-alarm/pull/4

Works after trial and error:
https://github.com/bbelderbos/pybites-alarm/actions/runs/1270663703

Nice to get this working here too

**Comment by pybites** [comment]
Tox: https://github.com/PyBites-Open-Source/pybites-alarm/blob/main/pyproject.toml

Could also go for nox: https://github.com/PyBites-Open-Source/biteme/blob/main/noxfile.py

**Comment by bbelderbos** [comment]
done
